# Generated by Django 3.2.5 on 2022-07-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(default=111)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField(blank=True)),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
                'unique_together': {('sku', 'product_name')},
            },
        ),
    ]
